### ISSUE TITLE
Greasemonkey 1.0 

### ISSUE THREAD

**Issue by kaefer** [cubiq/iscroll#256]
Hi, 
after updating Greasemonkey to 1.0 my script returns an error: "that.refresh is not a function". This error doesn't occur if I either deactivate the iscroll.js or downgrade Greasemonkey to 0.9.20. So the problem is (in my opinion) not within my JS-code. 
I use iscroll.js with this code-snippet and without any custom options: 
myscroll = new iScroll('wrapper');
the wrapper-element is a normal div with ID "wrapper".
Problem occurs with iscroll.js v4.2.2  

Thanks in advance for tips/workaround (except keeping GM 0.9.20)/update, 
kaefer
